In [31]:
# 1.Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

numbers = [10, 20, 30, 40, 50]
print("Original list:", numbers)

# append
numbers.append(60)
print("After append(60):", numbers)

# extend
numbers.extend([70, 80])
print("After extend([70, 80]):", numbers)

# insert
numbers.insert(2, 25)  # inserts 25 at index 2
print("After insert(2, 25):", numbers)

# remove
numbers.remove(40)
print("After remove(40):", numbers)

# pop
popped_element = numbers.pop()
print("After pop():", numbers)
print("Popped element:", popped_element)

# index
index_of_30 = numbers.index(30)
print("Index of 30:", index_of_30)

# count
count_of_20 = numbers.count(20)
print("Count of 20:", count_of_20)

# sort
numbers.sort()
print("After sort():", numbers)

# reverse
numbers.reverse()
print("After reverse():", numbers)

# clear (at the very end)
numbers.clear()
print("After clear():", numbers)

Original list: [10, 20, 30, 40, 50]
After append(60): [10, 20, 30, 40, 50, 60]
After extend([70, 80]): [10, 20, 30, 40, 50, 60, 70, 80]
After insert(2, 25): [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove(40): [10, 20, 25, 30, 50, 60, 70, 80]
After pop(): [10, 20, 25, 30, 50, 60, 70]
Popped element: 80
Index of 30: 3
Count of 20: 1
After sort(): [10, 20, 25, 30, 50, 60, 70]
After reverse(): [70, 60, 50, 30, 25, 20, 10]
After clear(): []


In [32]:
# 2.Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.
students = ("Ravi", "Raju", "kiran")
print("Original tuple:", students)
students[1] = "Akshay"
# In python tuple is immutable , Which means we can't Change its elements  once Created.

Original tuple: ('Ravi', 'Raju', 'kiran')


TypeError: 'tuple' object does not support item assignment

In [33]:
# 3.Create a set of integers with some duplicate values. Print the set and explain the output.
numbers = {12, 15, 20, 12, 15, 20, 30,30}
print("Set:", numbers)
# A set in Python is a collection of unique and unordered elements. When we create a set with duplicate values, Python automatically removes the duplicates and keeps only one copy of each element.

Set: {12, 20, 30, 15}


In [34]:
# 4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.
student = {
    "name": "Ravi",
    "age": 24,
    "city": "Mysore"
}
print("Original dictionary:", student)


student["age"] = 28


student["email"] = "Ravi@123.com"


print("Final dictionary:", student)


Original dictionary: {'name': 'Ravi', 'age': 24, 'city': 'Mysore'}
Final dictionary: {'name': 'Ravi', 'age': 28, 'city': 'Mysore', 'email': 'Ravi@123.com'}


In [35]:
# 5.  Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

age = int(input("Enter your age: "))


if age >= 18:
    print("You are eligible to vote ✅")
else:
    print("You are not eligible to vote ❌")

Enter your age:  17


You are not eligible to vote ❌


In [36]:
# 6. Given a 'marks' variable, print the grade:- 90 and above: 'A'- 75–89: 'B'- 50–74: 'C'- Below 50: 'Fail' Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.



marks = int(input("Enter your marks: "))

if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Grade: Fail")



Enter your marks:  95


Grade: A


In [37]:
# 7. Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

num = int(input("enter value: "))
if num > 0:
    if num % 2 == 0:
        print("Positive and Even")
    else:
        print("Positive but Odd")
elif num == 0:
    print("Zero")
else:
    print("Negative")

enter value:  5


Positive but Odd


In [38]:
# 8. Create:- 
# A scalar using np.array(5)
# - A 1D array with values 1 to 5
# - A 2D array (2x3) with values from 10 to 60 in steps of 10

import numpy as np
# Scalar
scalar = np.array(5)
print("Scalar:", scalar)
print("Shape:", scalar.shape)
print()
# 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)
print("Shape:", array_1d.shape)
print()
# 2d array
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60]])
print("2D Array:\n", array_2d)
print("Shape:", array_2d.shape)

Scalar: 5
Shape: ()

1D Array: [1 2 3 4 5]
Shape: (5,)

2D Array:
 [[10 20 30]
 [40 50 60]]
Shape: (2, 3)


In [39]:
# 9. Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

import numpy as np
random_array = np.random.randint(0, 100, size=(4, 4))

print("4x4 Random Integer Array:\n", random_array)

4x4 Random Integer Array:
 [[43 84 17 87]
 [47 12 58 92]
 [12 82 10 78]
 [78 36  6 60]]


In [40]:
# 10. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

import numpy as np
import pandas as pd

array_2d = np.array([[10, 15, 20],
                     [25, 30, 35],
                     [40, 45, 50]])
print("NumPy Array:\n", array_2d)
print()


df = pd.DataFrame(array_2d, columns=['A', 'B', 'C'])


print("Pandas DataFrame:\n", df)

NumPy Array:
 [[10 15 20]
 [25 30 35]
 [40 45 50]]

Pandas DataFrame:
     A   B   C
0  10  15  20
1  25  30  35
2  40  45  50


In [41]:
# 11. Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
# - Use .info(), .describe()
# - Select 'Name' and 'City' columns
# - Drop 'City' column
# - Fill any missing values in 'Salary' column with the mean
# - Remove any duplicate rows

import pandas as pd
import numpy as np

data = {
    'Name': ['Sandesh', 'Raju', 'Sahil', 'Ravi', 'Priyanka', 'Ganesh', 'Anand', 'Veda', 'Raghavendra', 'Pallavi'],
    'Age': [15, 25, 25, 22, 27, 29, 24, 27, 26, 30],
    'City': ['Bangalore', 'Hyderabad', 'Pune', 'Delhi', 'Bangalore', 'Delhi', 'Pune', 'Mumbai', 'Delhi', 'Bangalore'],
    'Salary': [35000,50000, 60000, 55000, np.nan, 60000, 45000, 52000, 60000, np.nan]
}

df = pd.DataFrame(data)

print("Original DataFrame:\n", df, "\n")

print("Info about DataFrame:")
print(df.info(), "\n")

print("Statistical Summary (.describe()):")
print(df.describe(), "\n")

print("Selected Columns (Name & City):")
print(df[['Name', 'City']], "\n")

df_dropped = df.drop(columns=['City'])
print("After dropping 'City' column:\n", df_dropped, "\n")

mean_salary = df['Salary'].mean()
df['Salary'] = df['Salary'].fillna(mean_salary)
print("After filling missing Salary values:\n", df, "\n")

df_no_duplicates = df.drop_duplicates().reset_index(drop=True)
print("After removing duplicate rows:\n", df_no_duplicates)

Original DataFrame:
           Name  Age       City   Salary
0      Sandesh   15  Bangalore  35000.0
1         Raju   25  Hyderabad  50000.0
2        Sahil   25       Pune  60000.0
3         Ravi   22      Delhi  55000.0
4     Priyanka   27  Bangalore      NaN
5       Ganesh   29      Delhi  60000.0
6        Anand   24       Pune  45000.0
7         Veda   27     Mumbai  52000.0
8  Raghavendra   26      Delhi  60000.0
9      Pallavi   30  Bangalore      NaN 

Info about DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None 

Statistical Summary (.describe()):
            Age        Salary
count  10.00000      8.000000
mean   25.00000  52125.